version: '3.3'

services:

# ======================================================================
# Language
# ======================================================================

  php7fpm1:
    image: codestep/php7phalcon:7.2.0
    container_name: docker-php7fpm1
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - VIRTUAL_PORT=9000
      - TERM=xterm
    volumes:
      - ./application:/usr/share/nginx/html/application
      - ./runtime:/usr/share/nginx/html/runtime
      - ./public:/usr/share/nginx/html/public
      - ./php7.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    networks:
      - frontend_network

# ======================================================================
# Web Server
# ======================================================================

  main:
    image: nginx:1.12.2-alpine
    container_name: docker-main
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
     - VIRTUAL_HOST=location
     - VIRTUAL_PORT=80
     - NGINX_HOST=location
     - NGINX_PORT=80
     - TERM=xterm
    volumes:
      - ./application:/usr/share/nginx/html/application
      - ./runtime:/usr/share/nginx/html/runtime
      - ./public:/usr/share/nginx/html/public
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "php7fpm1:phpfpm"
    ports:
      - "80:80"
    networks:
      - frontend_network

networks:
  frontend_network: